plugins {
    id 'com.android.application'
}

android {
    namespace 'com.lingyicute.orientationlock'
    compileSdk 34

    defaultConfig {
        applicationId "com.lingyicute.orientationlock"
        minSdk 21
        targetSdk 34
        versionCode 6
        versionName "1.6"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    def lifecycle_version = "2.7.0"
    def compose_version = "1.6.0"
    def hilt_version = "2.50"

    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.core:core:1.12.0'  // 添加 AndroidX Core 依赖
    
    // Lifecycle components
    // ... existing code ...

    testImplementation 'junit:junit:4.13.2'
}