name: Create Release

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: 8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build APK
      run: |
        cd ${{ github.workspace }}
        chmod 755 gradlew
        ./gradlew assembleDebug

    - name: Tree
      run: find /home/runner -type f -name "*.apk"

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build_apk
        path: /home/runner/work/YiTate/YiTate/app/build/outputs/apk/debug/app-debug.apk
