name: Create Release

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: rm
      run: rm -rf /home/runner/.gradle

    - name: Gradle build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Tree
      run: find /home/runner -type f -name "*.apk"

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build_apk
        path: ${{ env.APK_PATH }}
